server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS:localhost}:${POSTGRES_DB_SERVER_PORT:5432}/
        username: ${POSTGRES_USER:postgres}
        password: ${POSTGRES_PASSWORD:postgres}

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
            show-sql: true
            format-sql: true
            type: info
            use-sql-comments: true
            properties:
                hibernate.use_sql_comments: true
                hibernate.format_sql: true

springdoc:
    show-actuator: true
    paths-to-match: /**
    packages-to-scan: com.lashewi.boilerplate.springboot

# ===============================
# = HEALTH
# ===============================
management:
    endpoint:
        health:
            show-details: ALWAYS
        endpoints:
            web:
                exposure:
                    include: "*"

# ===============================
# = LOGS
# ===============================
logging:
    level:
        org.springframework: INFO
        com.lashewi.boilerplate.springboot: INFO

# ===============================
# = DOCUMENTATION
# ===============================
swagger:
    contact-name: Lakshitha Wisumperuma
    contact-mail: swisum@gmail.com
    contact-url: https://lakshitha.blog
    app-name: Spring Boot Boilerplate Project
    app-description: "Spring Boot Boilerplate is a starter kit. This project includes : Spring Boot(3.20), Spring Data JPA, Spring Validation, Spring Security, PostgreSQL, Mapstruct, Lombok, Swagger"
    app-version: 2.0.0
    app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
    app-license: Apache 2.0